// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/awards': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/awards.get').default>>>>
    }
    '/api/compound': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/compound.get').default>>>>
    }
    '/api/construction': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/construction.get').default>>>>
    }
    '/api/designersPage': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/designersPage.get').default>>>>
    }
    '/api/detailPageInfo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/detailPageInfo.get').default>>>>
    }
    '/api/infocontacts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/infocontacts.get').default>>>>
    }
    '/api/labBanner': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/labBanner.get').default>>>>
    }
    '/api/labBottom': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/labBottom.get').default>>>>
    }
    '/api/labInfoAfterBanner': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/labInfoAfterBanner.get').default>>>>
    }
    '/api/labObjects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/labObjects.get').default>>>>
    }
    '/api/labPark': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/labPark.get').default>>>>
    }
    '/api/labPrices': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/labPrices.get').default>>>>
    }
    '/api/mainAboutCompany': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mainAboutCompany.get').default>>>>
    }
    '/api/mainBanner': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mainBanner.get').default>>>>
    }
    '/api/mainBottomBanner': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mainBottomBanner.get').default>>>>
    }
    '/api/mainSliderBottom': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mainSliderBottom.get').default>>>>
    }
    '/api/mainTextImage': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mainTextImage.get').default>>>>
    }
    '/api/mainTrust': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mainTrust.get').default>>>>
    }
    '/api/menu': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu.get').default>>>>
    }
    '/api/news': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/news.get').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products.get').default>>>>
    }
    '/api/productsList': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/productsList.get').default>>>>
    }
    '/api/services': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/services.get').default>>>>
    }
    '/api/serviceSeo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/serviceSeo.get').default>>>>
    }
    '/api/servicesTop': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/servicesTop.get').default>>>>
    }
    '/api/threeBlockMain': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/threeBlockMain.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}